# Generated by Django 5.2.4 on 2025-07-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeveloperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.CharField(help_text='MongoDB ObjectId of the developer', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Developer Link',
                'verbose_name_plural': 'User Developer Links',
                'unique_together': {('user', 'developer_id')},
            },
        ),
    ]
