# Generated by Django 5.2.4 on 2025-07-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrepository',
            name='github_repo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
