# Generated by Django 5.2.4 on 2025-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationrepository_github_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
