# Generated by Django 5.2.4 on 2025-08-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ossindexconfig',
            name='email',
            field=models.EmailField(blank=True, help_text='OSS Index account email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ossindexconfig',
            name='api_token',
            field=models.CharField(blank=True, help_text='OSS Index API token', max_length=500, null=True),
        ),
    ]
