# Generated by Django 5.2.4 on 2025-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0003_remove_ossindexconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('sonarcloud', 'SonarCloud')], max_length=50)),
                ('name', models.CharField(help_text="Admin label, e.g., 'GitHub - Org Foo'", max_length=100)),
                ('github_organization', models.CharField(blank=True, help_text='Target GitHub organization login (owner). Leave blank for default/global.', max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
                'indexes': [models.Index(fields=['provider', 'github_organization', 'status'], name='management__provide_881f31_idx')],
            },
        ),
    ]
