# Generated by Django 5.2.4 on 2025-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access token used for API calls (OAuth access token or fine-grained PAT)', max_length=500),
        ),
    ]
