# Generated by Django 5.2.4 on 2025-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_integrationconfig_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationconfig',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='app_id',
            field=models.CharField(blank=True, help_text='GitHub App ID', max_length=50),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='installation_id',
            field=models.CharField(blank=True, help_text='GitHub App Installation ID for this organization', max_length=50),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='private_key',
            field=models.TextField(blank=True, help_text='GitHub App Private Key (PEM)'),
        ),
    ]
