# Generated by Django 5.2.4 on 2025-08-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_integrationconfig_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationconfig',
            name='installation_id',
        ),
    ]
