site_name: GitPulse
site_description: GitHub Analytics Dashboard for CTOs and Tech Leads
site_author: assia_dialeb
site_url: https://assiadialeb.github.io/gitpulse/

repo_name: assiadialeb/gitpulse
repo_url: https://github.com/assiadialeb/gitpulse
edit_uri: edit/main/docs/

theme:
  name: material
  logo: null
  icon:
    logo: material/git
  language: en
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    #- toc.integrate
    #- header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
#  - stylesheets/extra.css
# Important: disables pretty URLs for GitHub Pages compatibility
use_directory_urls: false

plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 70%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_themed: false
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption


nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - User Guide:
      - Overview: user-guide/overview.md
      - GitHub Setup: user-guide/github-setup.md
      - Repository :
          - Overview: user-guide/repositories/overview.md
          - Commit Frequency: user-guide/repositories/commit-frequency.md
          - Commit Classification: user-guide/repositories/commit-classification.md
          - Pull Requests: user-guide/repositories/pull-requests.md
          - Releases: user-guide/repositories/releases.md
          - Deployments: user-guide/repositories/deployments.md
          - Security Health Score: user-guide/repositories/security-health-score.md
          - SonarCloud Metrics: user-guide/repositories/sonarcloud-metrics.md
          - Licensing: user-guide/repositories/licensing.md
          
      - Project Analytics:
          - Overview: user-guide/projects/overview.md
      - Developer Analytics: user-guide/developers.md
  - Technical Documentation:
      - Architecture: technical/architecture.md
      - API Reference: technical/api.md
      - Management Commands: technical/management-commands.md
      - Troubleshooting: technical/troubleshooting.md
  - Deployment:
      - Docker: deployment/docker.md
      - Production: deployment/production.md
      - GitHub Pages: deployment/github-pages.md
  - Releases : https://github.com/assiadialeb/gitpulse/releases