site_name: GitPulse
site_description: GitHub Analytics Dashboard for CTOs and Tech Leads
site_author: GitPulse Team
site_url: https://assiadialeb.github.io/

repo_name: assiadialeb/gitpulse
repo_url: https://github.com/assiadialeb/gitpulse
edit_uri: edit/main/docs/

theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - GitHub Setup: user-guide/github-setup.md
    - Projects: user-guide/projects.md
    - Analytics: user-guide/analytics.md
    - Developers: user-guide/developers.md
  - Technical Documentation:
    - Architecture: technical/architecture.md
    - API Reference: technical/api.md
    - Management Commands: technical/management-commands.md
    - Troubleshooting: technical/troubleshooting.md
  - Deployment:
    - Docker: deployment/docker.md
    - Production: deployment/production.md
    - GitHub Pages: deployment/github-pages.md 