# Generated by Django 5.2.4 on 2025-07-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=10)),
            ],
            options={
                'verbose_name': 'Installation Log',
                'verbose_name_plural': 'Installation Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InstallationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('superuser', 'SuperUser Creation'), ('github_oauth', 'GitHub OAuth Configuration'), ('schedules', 'Task Schedules')], max_length=20, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Installation Step',
                'verbose_name_plural': 'Installation Steps',
            },
        ),
    ]
