# Generated by Django 5.2.4 on 2025-07-20 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('fork', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('ssh_url', models.URLField()),
                ('is_indexed', models.BooleanField(default=False)),
                ('last_indexed', models.DateTimeField(blank=True, null=True)),
                ('commit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-updated_at'],
            },
        ),
    ]
