# Generated by Django 5.2.4 on 2025-07-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_indexing',
            field=models.BooleanField(default=False),
        ),
    ]
