# Generated by Django 5.2.4 on 2025-07-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_is_indexing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='is_indexing',
        ),
    ]
