# Generated by Django 5.2.4 on 2025-08-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0003_remove_is_indexing_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="kloc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="repository",
            name="kloc_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
