# Generated by Django 5.2.4 on 2025-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0004_repository_kloc_repository_kloc_calculated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="kloc",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="kloc_calculated_at",
        ),
    ]
