# Generated by Django 5.2.4 on 2025-07-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=100)),
                ('redirect_uri', models.URLField()),
                ('webhook_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('app_id', models.IntegerField(unique=True)),
                ('repo_permissions', models.JSONField(default=dict)),
                ('org_permissions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub App',
                'verbose_name_plural': 'GitHub Apps',
            },
        ),
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.IntegerField(unique=True)),
                ('account_type', models.CharField(choices=[('User', 'User'), ('Organization', 'Organization')], max_length=20)),
                ('account_id', models.IntegerField()),
                ('account_login', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=dict)),
                ('repositories', models.JSONField(default=list)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Installation',
                'verbose_name_plural': 'GitHub Installations',
            },
        ),
        migrations.CreateModel(
            name='GitHubOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub OAuth State',
                'verbose_name_plural': 'GitHub OAuth States',
            },
        ),
        migrations.CreateModel(
            name='GitHubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('token_type', models.CharField(default='bearer', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('github_user_id', models.IntegerField()),
                ('github_username', models.CharField(max_length=100)),
                ('github_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Token',
                'verbose_name_plural': 'GitHub Tokens',
            },
        ),
    ]
