# Generated by Django 5.2.4 on 2025-07-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubapp',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='githubapp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='githubapp',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='githubapp',
            name='redirect_uri',
        ),
        migrations.RemoveField(
            model_name='githubapp',
            name='webhook_secret',
        ),
    ]
