# Generated by Django 5.2.4 on 2025-07-14 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'developers',
                'indexes': [models.Index(fields=['name', 'email'], name='developers_name_389a06_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commit_count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='developers.developer')),
            ],
            options={
                'db_table': 'developer_aliases',
                'indexes': [models.Index(fields=['name', 'email'], name='developer_a_name_bdedaa_idx'), models.Index(fields=['developer'], name='developer_a_develop_c7c5ee_idx')],
                'unique_together': {('name', 'email')},
            },
        ),
    ]
