# Generated by Django 5.2.4 on 2025-07-12 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'developer_groups',
                'indexes': [models.Index(fields=['name', 'email'], name='developer_g_name_aa546f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeveloperIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commit_count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='developers.developergroup')),
            ],
            options={
                'db_table': 'developer_identities',
                'indexes': [models.Index(fields=['name', 'email'], name='developer_i_name_4fe35c_idx'), models.Index(fields=['group'], name='developer_i_group_i_fdc9cd_idx')],
                'unique_together': {('name', 'email')},
            },
        ),
    ]
