# Generated by Django 5.2.4 on 2025-08-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="github_organizations",
            field=models.JSONField(
                blank=True, default=list, help_text="List of GitHub organization names"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="github_teams",
            field=models.JSONField(
                blank=True, default=list, help_text="List of GitHub team slugs"
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="primary_team",
            field=models.CharField(
                blank=True, help_text="Main team for this developer", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="team_role",
            field=models.CharField(
                blank=True,
                help_text="Role in the team (member, admin, etc.)",
                max_length=50,
            ),
        ),
    ]
