name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'mkdocs.yml', 'CNAME' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'mkdocs.yml', 'CNAME' ]
  workflow_dispatch:

# Add permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

    - name: Clean previous site folder
      run: rm -rf site/

    - name: Build documentation
      run: mkdocs build --clean

    - name: Check links
      run: |
        pip install linkchecker
        linkchecker site/ || true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

    - name: Clean previous site folder
      run: rm -rf site/

    - name: Build documentation
      run: mkdocs build --clean

    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ${{ github.workspace }}/site
        force_orphan: true
        enable_jekyll: false  # important for Material theme on GitHub Pages