name: Build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CNAME'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CNAME'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      # v5 inclut le cache pip natif
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Setup test database
        env:
          PYTEST: "1"
        run: |
          # Create database tables without running problematic migrations
          python manage.py migrate --run-syncdb || python tests/setup_test_db.py

      - name: Pytest (JUnit + Coverage)
        env:
          PYTEST: "1"
        run: |
          mkdir -p reports
          pytest \
            --junitxml=reports/junit-${{ matrix.python-version }}.xml \
            --cov=. --cov-report=xml:reports/coverage-${{ matrix.python-version }}.xml \
            --cov-report=term-missing

      - name: Upload reports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.python-version }}
          path: reports/

  sonar:
    name: SonarQube
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # conseillé par Sonar

      # Récupère un des coverage.xml du matrix (tu peux aussi agréger)
      - name: Download coverage artifact (3.11)
        uses: actions/download-artifact@v4
        with:
          name: test-reports-3.11
          path: reports

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io